_target_: src.lightning_modules.SimpleVAE

latent_dim: 10

encoder:
  _target_: src.networks.ImageMLPEncoder
  height: 32
  width: 32
  channels: 1
  output_dim: ${latent_dim}

decoder:
  _target_: src.networks.ImageMLPDecoder
  height: 32
  width: 32
  channels: 1
  input_dim: ${latent_dim}