_target_: src.lightning_modules.I2SB
model:
  _target_: src.networks.UNet2D
  in_channels: 1
  out_channels: 1
  block_out_channels: [32, 64, 64]
  down_block_types: ['DownBlock2D', 'DownBlock2D', 'DownBlock2D']
  up_block_types: ['UpBlock2D', 'UpBlock2D', 'UpBlock2D']

num_steps: 100
min_beta: 0.1
max_beta: 1
T: 1.0